version: '3'

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongo
      - redis
    restart: on-failure
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules

  mongo:
    image: mongo:latest
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    restart: always
    volumes:
      - .data:/data/db

  redis:
    image: redis:latest
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    restart: always
    volumes:
      - .cache:/data

volumes:
  mongo:
    driver: local
  cache:
    driver: local
