module.exports = {
  TOKEN_NOT_FOUND: 'TOKEN_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USERNAME_EXISTED: 'USERNAME_EXISTED',
  INCORRECT_USERNAME_OR_PASSWORD: 'INCORRECT_USERNAME_OR_PASSWORD',
};
